### ISSUE TITLE
Does not seem to be working

### ISSUE THREAD

**Issue by PeterChia604** [qqaatw/taipower-ha#1]
Just tried out the Taipower Integration.
It complained.  

-----------------------------------------------------------
Log Details (ERROR)

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/taipower_tw/__init__.py:148
Integration: Taipower TW (documentation, issues)
First occurred: 01:43:22 (1 occurrences)
Last logged: 01:43:22

Error setting up entry Taipower TW for taipower_tw
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/taipower_tw/__init__.py", line 148, in async_setup_entry
    await hass.async_add_executor_job(api.login)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Taipower/api.py", line 260, in login
    conn = connection.GetMember(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Taipower/connection.py", line 288, in __init__
    super().__init__(account, password, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/Taipower/connection.py", line 54, in __init__
    conn_status, self._taipower_tokens = self.login()
                                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Taipower/connection.py", line 158, in login
    status, response = asyncio.run(self._async_send("oauth/token", data=login_json_data, headers=login_headers))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Taipower/connection.py", line 121, in _async_send
    message, response_json = self._handle_response(req)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Taipower/connection.py", line 68, in _handle_response
    response_json = response.json()
                    ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

-----------------------------------------------------------
Log Details (WARNING)

Logger: homeassistant.components.number
Source: components/number/__init__.py:114
Integration: Number (documentation, issues)
First occurred: 01:43:23 (2 occurrences)
Last logged: 01:43:23

custom_components.taipower_tw.number::TaipowerBillMonthSelectorNumberEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.taipower_tw.number::TaipowerAMISelectorNumberEntity is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by qqaatw** [comment]
I'm afraid I won't have time to investigate the issue in the near future. 

We accept PRs fixing it.
